service: service-external

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  profile: BTP
  stage: prod

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref": "IamRoleLambdaExecution"}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"

custom:
  domains:
    prod: api.lostmywheels.com
    dev: dev-api.lostmywheels.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: '*.lostmywheels.com'
    basePath: 'external'
    stage: ${self:custom.stage}
    createRoute53Record: true
  stage: ${opt:stage, self:provider.stage}
  dotenv:
    basePath: '../'
    logging: false
  cors:
    origins:
      - '*'

functions:
  get_dvla:
    handler: external.get_dvla_data
    events:
      - http:
          path: dvla
          method: POST
          cors: { $self:custom.cors }
