service: service-forum

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: prod
  profile: BTP
  vpc:
    securityGroupIds:
      - sg-92c883f5
    subnetIds:
      - subnet-41ed773b
      - subnet-653e9729
      - subnet-ca7826a3

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref": "IamRoleLambdaExecution"}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"

custom:
  domains:
    prod: api.lostmywheels.com
    dev: dev-api.lostmywheels.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: '*.lostmywheels.com'
    basePath: 'forum'
    stage: ${self:custom.stage}
    createRoute53Record: true
  stage: ${opt:stage, self:provider.stage}
  dotenv:
    basePath: '../'
    logging: false
  cors:
    origins:
      - '*'

functions:
  get:
    handler: forum.get
    events:
      - http:
          path: get
          method: POST
          cors: {$self:custom.cors}
